
# Modelo Estrella

En analítica de datos es común organizar la información en un **modelo dimensional**.

- **Tabla de hechos:** contiene las métricas del negocio.
- **Tablas de dimensión:** contienen el contexto de las métricas.

En este ejercicio:

**fact_ventas**
- id_tienda
- id_producto
- fecha
- cantidad
- precio

**dim_tienda**
- id_tienda
- nombre_tienda
- ciudad

**dim_producto**
- id_producto
- nombre_producto
- categoria

In [1]:
import pandas as pd

In [5]:
dff= pd.read_csv('/content/FACT_VENTAS_MASTER.csv')
dfdp= pd.read_csv('/content/DIM_PRODUCTOS (2).csv')
dfdt= pd.read_csv('/content/DIM_TIENDAS.csv')

**Fact Ventas**

In [6]:
dff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Venta_ID             10000 non-null  object
 1   Fecha_ISO            10000 non-null  object
 2   Tienda_ID            10000 non-null  object
 3   SKU_ID               10000 non-null  object
 4   Pais_Venta           10000 non-null  object
 5   CLIENTE_NOMBRE_PII   10000 non-null  object
 6   CLIENTE_EMAIL_PII    10000 non-null  object
 7   CLIENTE_EDAD_PII     8996 non-null   float64
 8   Moneda_Transaccion   10000 non-null  object
 9   Monto_Total_Local    10000 non-null  float64
 10  Impuesto_Local       10000 non-null  float64
 11  Tasa_Referencia_Dia  10000 non-null  float64
 12  Metodo_Pago          7982 non-null   object
 13  Es_Online            10000 non-null  object
 14  Canal_Origen         10000 non-null  object
 15  Costo_Envio_USD      10000 non-null  float64
 16  Latitud_Tienda       10000 non-null  float64
 17  Longitud_Tienda      10000 non-null  float64
 18  Browser_User_Agent   10000 non-null  object
 19  ID_Session_Web       10000 non-null  object
 20  Flag_Fraude          10000 non-null  int64
 21  Version_Esquema      10000 non-null  object
 22  Ref_S3_TXT           10000 non-null  object
dtypes: float64(7), int64(1), object(15)
memory usage: 1.8+ MB

In [7]:
dff.head(5)

,Venta_ID,Fecha_ISO,Tienda_ID,SKU_ID,Pais_Venta,CLIENTE_NOMBRE_PII,CLIENTE_EMAIL_PII,CLIENTE_EDAD_PII,Moneda_Transaccion,Monto_Total_Local,...,Es_Online,Canal_Origen,Costo_Envio_USD,Latitud_Tienda,Longitud_Tienda,Browser_User_Agent,ID_Session_Web,Flag_Fraude,Version_Esquema,Ref_S3_TXT
0,TXN-600000,2025-08-11T15:00:20.491637,STORE-001,SKU-00077,UK,Null User,user_0@uk.com,44.0,GBP,1024.76,...,No,App,34.67,-18.0086,0.0843,Mozilla/5.0... (Simulado),0xcb2c83f6,0,v2.4.1,TXN-600000.txt
1,TXN-600001,2026-01-29T15:00:20.511040,STORE-017,SKU-00008,USA,Müller S.,user_1@usa.com,33.0,USD,706.16,...,No,App,45.37,-38.3724,127.3740,Mozilla/5.0... (Simulado),0xd141323f,0,v2.4.1,TXN-600001.txt
2,TXN-600002,2025-10-30T15:00:20.526154,STORE-009,SKU-00082,USA,Müller S.,user_2@usa.com,25.0,USD,1394.57,...,True,Web,25.97,15.9027,-47.2338,Mozilla/5.0... (Simulado),0x74f10ced,0,v2.4.1,TXN-600002.txt
3,TXN-600003,2025-06-06T15:00:20.545533,STORE-013,SKU-00112,USA,Müller S.,user_3@usa.com,27.0,USD,1196.51,...,0,App,24.61,-76.6412,-88.2098,Mozilla/5.0... (Simulado),0x14137032,0,v2.4.1,TXN-600003.txt
4,TXN-600004,2025-05-01T15:00:20.566309,STORE-005,SKU-00090,México,Müller S.,user_4@méxico.com,28.0,MXN,2771.44,...,True,App,44.01,66.3781,57.1449,Mozilla/5.0... (Simulado),0x9671de31,0,v2.4.1,TXN-600004.txt

**Dimensión Tiendas**

In [8]:
dfdt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Tienda_ID      20 non-null     object
 1   Nombre_Tienda  20 non-null     object
 2   Pais           20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [9]:
dfdt.head(5)

   Tienda_ID            Nombre_Tienda      Pais
0  STORE-001        GlobalTech UK - 1        UK
1  STORE-002       GlobalTech USA - 2       USA
2  STORE-003  GlobalTech Colombia - 3  Colombia
3  STORE-004  GlobalTech Colombia - 4  Colombia
4  STORE-005    GlobalTech México - 5    México

**Dimensión Productos**

In [10]:
dfdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   SKU_ID           150 non-null    object
 1   Nombre_Producto  150 non-null    object
 2   Categoria        150 non-null    object
 3   Costo_Base_USD   150 non-null    float64
dtypes: float64(1), object(3)
memory usage: 4.8+ KB

In [14]:
dfdp.head(5)

      SKU_ID Nombre_Producto    Categoria  Costo_Base_USD
0  SKU-00001   Gadget Pro X1      Oficina         1040.91
1  SKU-00002   Gadget Pro X2  Electr0nica          381.08
2  SKU-00003   Gadget Pro X3        Hogar         1044.33
3  SKU-00004   Gadget Pro X4     Ofic_Ina         1079.42
4  SKU-00005   Gadget Pro X5        Hogar          449.40